"""Initial revision

Revision ID: 349544795a61
Revises:
Create Date: 2024-11-30 14:48:07.450433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "349544795a61"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_period",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("applicable_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("applicable_date"),
    )
    op.create_table(
        "rate_detail",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("cargo_type", sa.String(), nullable=False),
        sa.Column("rate_period_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rate_period_id"],
            ["rate_period.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate_detail")
    op.drop_table("rate_period")
    # ### end Alembic commands ###
