"""Renamed tables

Revision ID: 736552ac9cfa
Revises: 349544795a61
Create Date: 2024-11-30 14:51:54.623404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "736552ac9cfa"
down_revision: Union[str, None] = "349544795a61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_periods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("applicable_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("applicable_date"),
    )
    op.create_table(
        "rate_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("cargo_type", sa.String(), nullable=False),
        sa.Column("rate_period_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rate_period_id"],
            ["rate_periods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("rate_detail")
    op.drop_table("rate_period")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_detail",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "cargo_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "rate_period_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rate_period_id"],
            ["rate_period.id"],
            name="rate_detail_rate_period_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="rate_detail_pkey"),
    )
    op.create_table(
        "rate_period",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "applicable_date",
            sa.DATE(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="rate_period_pkey"),
        sa.UniqueConstraint(
            "applicable_date", name="rate_period_applicable_date_key"
        ),
    )
    op.drop_table("rate_details")
    op.drop_table("rate_periods")
    # ### end Alembic commands ###
