services:
  app:
    image: smbrine/api-test-task:v1
    environment:
      POSTGRES_ENDPOINT: postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      BIND_HOST: 0.0.0.0
      BIND_PORT: 8000
      CARGO_TYPES: Glass;Other
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
  migration:
    image: smbrine/api-test-task:v1
    command: bash -c "alembic upgrade head && python -m app.main --generate-rates --upload-rates --exit-on-upload"
    environment:
      POSTGRES_ENDPOINT: postgresql+asyncpg://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17.2-bullseye
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/pgdata
#    volumes:
#      - ${DATA_DIR}/postgres/postgres-data:/var/lib/postgresql/pgdata # Uncomment to enable persistence
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"